### ISSUE TITLE
bytes vs. text  and python 3

### ISSUE THREAD

**Issue by edelmann** [apel/ssm#146]
Hello!

I recently installed ssm apel_ssm-3.1.1 with python3.5, but kept getting

`AttributeError: 'bytes' object has no attribute 'encode'` 

all the time.  Turned out those exceptions came from the call to crypto.sign in _send_msg_ams, because 'text' is really a list of bytes.  If I change the line

`to_send = crypto.sign(text, self._cert, self._key`

into

`to_send = crypto.sign(text.decode('utf8'), self._cert, self._key)`

it works.

**Comment by edelmann** [comment]
A somewhat better approach might be to decode 'text' immediately when we get it:

```
ssm/ssm$ git diff
diff --git a/ssm/ssm2.py b/ssm/ssm2.py
index 735056b..9831e0c 100644
--- a/ssm/ssm2.py
+++ b/ssm/ssm2.py
@@ -478,6 +478,8 @@ class Ssm2(stomp.ConnectionListener):
                 continue
 
             text = self._outq.get(msgid)
+            if type(text) == bytes:
+                text = text.decode('utf8')
 
             if self._protocol == Ssm2.STOMP_MESSAGING:
                 # Then we are sending to a STOMP message broker.
```

(Looks like it's working to me, but not thoroughly tested)

**Comment by tofu-rocketry** [comment]
Also reported [here](https://ggus.eu/index.php?mode=ticket_info&ticket_id=147790#update#61).

**Comment by tofu-rocketry** [comment]
We're still developing our Python 3 support at the moment, which would explain this. I'll give this a test and so long as it works in 2.7 I can implement it.

**Comment by andrejfilipcic** [comment]
I confirm the patch (2nd) works fine for me with python3.8.

Few more issues:

1)  installation does not work with separate build and install phase, I did this hack as a quick fix:
diff -ur ssm-3.1.1-1/setup.py ssm-3.1.1-1.af/setup.py
--- ssm-3.1.1-1/setup.py        2020-12-16 17:41:11.000000000 +0000
+++ ssm-3.1.1-1.af/setup.py     2021-01-19 09:04:42.441802686 +0000
@@ -25,7 +25,7 @@
 def main():
     """Called when run as script, e.g. 'python setup.py install'."""
     # Create temporary files with deployment names
-    if 'install' in sys.argv:
+    if 'install' not in sys.argv:
         copyfile('bin/receiver.py', 'bin/ssmreceive')
         copyfile('bin/sender.py', 'bin/ssmsend')
         copyfile('scripts/apel-ssm.logrotate', 'conf/apel-ssm')

2) In stomppy 6.1.0, the .start() func  was removed, so, this works for me.
diff -ur ssm-3.1.1-1/ssm/ssm2.py ssm-3.1.1-1.af/ssm/ssm2.py
--- ssm-3.1.1-1/ssm/ssm2.py     2021-01-20 13:09:12.464747089 +0000
+++ ssm-3.1.1-1.af/ssm/ssm2.py  2021-01-20 13:10:02.470458826 +0000
@@ -611,7 +611,6 @@
             raise Ssm2Exception('Called start_connection() before a \
                     connection object was initialised.')
 
-        self._conn.start()
         self._conn.connect(wait=False)
 
         i = 0

**Comment by tofu-rocketry** [comment]
So it looks like the original issue was resolved by an update to the AMS library that came out about the same time as the original report.

I'll create new issues to track the ones raised in https://github.com/apel/ssm/issues/146#issuecomment-763635805

**Comment by tofu-rocketry** [comment]
Spoke to soon. There was one issue hiding another.
